name: Building Program
run-name: Building ${{ GITHUB.REPOSITORY }}

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  call-bpo:
    uses: GXDE-OS/GXDE/.github/workflows/building-deb-tianlu-backport.yml@master
    secrets: inherit

  call-stable:
      uses: GXDE-OS/GXDE/.github/workflows/building-deb.yml@master
      secrets: inherit
